jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set base and head refs for manual runs'
        run: |
          if [ -z "${{ github.event.pull_request.base.ref }}" ]; then
            echo "BASE_REF=master" >> $GITHUB_ENV
            echo "HEAD_REF=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          else
            echo "BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
            echo "HEAD_REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          fi

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ env.BASE_REF }}
          head-ref: ${{ env.HEAD_REF }}
          comment-summary-in-pr: always
        env:
          GH_TOKEN: ${{ secrets.TOKEN_REPO }}