name: ShellCheck Linter

on:
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          path: $GITHUB_WORKSPACE/cross_compile_ffmpeg.sh
          severity: error
